# convert *Blastoise.ico[1] -resize 75% Blastoise.png


convert *Bulbasaur.ico[1] -resize 75% Bulbasaur.png
convert *Ivysaur.ico[1] -resize 75% Ivysaur.png
convert *Venusaur.ico[1] -resize 75% Venusaur.png
convert *Charmander.ico[1] -resize 75% Charmander.png
convert *Charmeleon.ico[1] -resize 75% Charmeleon.png
convert *Charizard.ico[1] -resize 75% Charizard.png
convert *Squirtle.ico[1] -resize 75% Squirtle.png
convert *Wartortle.ico[1] -resize 75% Wartortle.png
convert *Blastoise.ico[1] -resize 75% Blastoise.png
convert *Caterpie.ico[1] -resize 75% Caterpie.png
convert *Metapod.ico[1] -resize 75% Metapod.png
convert *Butterfree.ico[1] -resize 75% Butterfree.png
convert *Weedle.ico[1] -resize 75% Weedle.png
convert *Kakuna.ico[1] -resize 75% Kakuna.png
convert *Beedrill.ico[1] -resize 75% Beedrill.png
convert *Pidgey.ico[1] -resize 75% Pidgey.png
convert *Pidgeotto.ico[1] -resize 75% Pidgeotto.png
convert *Pidgeot.ico[1] -resize 75% Pidgeot.png
convert *Rattata.ico[1] -resize 75% Rattata.png
convert *Raticate.ico[1] -resize 75% Raticate.png
convert *Spearow.ico[1] -resize 75% Spearow.png
convert *Fearow.ico[1] -resize 75% Fearow.png
convert *Ekans.ico[1] -resize 75% Ekans.png
convert *Arbok.ico[1] -resize 75% Arbok.png
convert *Pikachu.ico[1] -resize 75% Pikachu.png
convert *Raichu.ico[1] -resize 75% Raichu.png
convert *Sandshrew.ico[1] -resize 75% Sandshrew.png
convert *Sandslash.ico[1] -resize 75% Sandslash.png
convert *NidoranF.ico[1] -resize 75% NidoranF.png
convert *Nidorina.ico[1] -resize 75% Nidorina.png
convert *Nidoqueen.ico[1] -resize 75% Nidoqueen.png
convert *NidoranM.ico[1] -resize 75% NidoranM.png
convert *Nidorino.ico[1] -resize 75% Nidorino.png
convert *Nidoking.ico[1] -resize 75% Nidoking.png
convert *Clefairy.ico[1] -resize 75% Clefairy.png
convert *Clefable.ico[1] -resize 75% Clefable.png
convert *Vulpix.ico[1] -resize 75% Vulpix.png
convert *Ninetales.ico[1] -resize 75% Ninetales.png
convert *Jigglypuff.ico[1] -resize 75% Jigglypuff.png
convert *Wigglytuff.ico[1] -resize 75% Wigglytuff.png
convert *Zubat.ico[1] -resize 75% Zubat.png
convert *Golbat.ico[1] -resize 75% Golbat.png
convert *Oddish.ico[1] -resize 75% Oddish.png
convert *Gloom.ico[1] -resize 75% Gloom.png
convert *Vileplume.ico[1] -resize 75% Vileplume.png
convert *Paras.ico[1] -resize 75% Paras.png
convert *Parasect.ico[1] -resize 75% Parasect.png
convert *Venonat.ico[1] -resize 75% Venonat.png
convert *Venomoth.ico[1] -resize 75% Venomoth.png
convert *Diglett.ico[1] -resize 75% Diglett.png
convert *Dugtrio.ico[1] -resize 75% Dugtrio.png
convert *Meowth.ico[1] -resize 75% Meowth.png
convert *Persian.ico[1] -resize 75% Persian.png
convert *Psyduck.ico[1] -resize 75% Psyduck.png
convert *Golduck.ico[1] -resize 75% Golduck.png
convert *Mankey.ico[1] -resize 75% Mankey.png
convert *Primeape.ico[1] -resize 75% Primeape.png
convert *Growlithe.ico[1] -resize 75% Growlithe.png
convert *Arcanine.ico[1] -resize 75% Arcanine.png
convert *Poliwag.ico[1] -resize 75% Poliwag.png
convert *Poliwhirl.ico[1] -resize 75% Poliwhirl.png
convert *Poliwrath.ico[1] -resize 75% Poliwrath.png
convert *Abra.ico[1] -resize 75% Abra.png
convert *Kadabra.ico[1] -resize 75% Kadabra.png
convert *Alakazam.ico[1] -resize 75% Alakazam.png
convert *Machop.ico[1] -resize 75% Machop.png
convert *Machoke.ico[1] -resize 75% Machoke.png
convert *Machamp.ico[1] -resize 75% Machamp.png
convert *Bellsprout.ico[1] -resize 75% Bellsprout.png
convert *Weepinbell.ico[1] -resize 75% Weepinbell.png
convert *Victreebel.ico[1] -resize 75% Victreebel.png
convert *Tentacool.ico[1] -resize 75% Tentacool.png
convert *Tentacruel.ico[1] -resize 75% Tentacruel.png
convert *Geodude.ico[1] -resize 75% Geodude.png
convert *Graveler.ico[1] -resize 75% Graveler.png
convert *Golem.ico[1] -resize 75% Golem.png
convert *Ponyta.ico[1] -resize 75% Ponyta.png
convert *Rapidash.ico[1] -resize 75% Rapidash.png
convert *Slowpoke.ico[1] -resize 75% Slowpoke.png
convert *Slowbro.ico[1] -resize 75% Slowbro.png
convert *Magnemite.ico[1] -resize 75% Magnemite.png
convert *Magneton.ico[1] -resize 75% Magneton.png
convert *Farfetch*.ico[1] -resize 75% Farfetch*.png
convert *Doduo.ico[1] -resize 75% Doduo.png
convert *Dodrio.ico[1] -resize 75% Dodrio.png
convert *Seel.ico[1] -resize 75% Seel.png
convert *Dewgong.ico[1] -resize 75% Dewgong.png
convert *Grimer.ico[1] -resize 75% Grimer.png
convert *Muk.ico[1] -resize 75% Muk.png
convert *Shellder.ico[1] -resize 75% Shellder.png
convert *Cloyster.ico[1] -resize 75% Cloyster.png
convert *Gastly.ico[1] -resize 75% Gastly.png
convert *Haunter.ico[1] -resize 75% Haunter.png
convert *Gengar.ico[1] -resize 75% Gengar.png
convert *Onix.ico[1] -resize 75% Onix.png
convert *Drowzee.ico[1] -resize 75% Drowzee.png
convert *Hypno.ico[1] -resize 75% Hypno.png
convert *Krabby.ico[1] -resize 75% Krabby.png
convert *Kingler.ico[1] -resize 75% Kingler.png
convert *Voltorb.ico[1] -resize 75% Voltorb.png
convert *Electrode.ico[1] -resize 75% Electrode.png
convert *Exeggcute.ico[1] -resize 75% Exeggcute.png
convert *Exeggutor.ico[1] -resize 75% Exeggutor.png
convert *Cubone.ico[1] -resize 75% Cubone.png
convert *Marowak.ico[1] -resize 75% Marowak.png
convert *Hitmonlee.ico[1] -resize 75% Hitmonlee.png
convert *Hitmonchan.ico[1] -resize 75% Hitmonchan.png
convert *Lickitung.ico[1] -resize 75% Lickitung.png
convert *Koffing.ico[1] -resize 75% Koffing.png
convert *Weezing.ico[1] -resize 75% Weezing.png
convert *Rhyhorn.ico[1] -resize 75% Rhyhorn.png
convert *Rhydon.ico[1] -resize 75% Rhydon.png
convert *Chansey.ico[1] -resize 75% Chansey.png
convert *Tangela.ico[1] -resize 75% Tangela.png
convert *Kangaskhan.ico[1] -resize 75% Kangaskhan.png
convert *Horsea.ico[1] -resize 75% Horsea.png
convert *Seadra.ico[1] -resize 75% Seadra.png
convert *Goldeen.ico[1] -resize 75% Goldeen.png
convert *Seaking.ico[1] -resize 75% Seaking.png
convert *Staryu.ico[1] -resize 75% Staryu.png
convert *Starmie.ico[1] -resize 75% Starmie.png
convert *Mime.ico[1] -resize 75% MrMime.png
convert *Scyther.ico[1] -resize 75% Scyther.png
convert *Jynx.ico[1] -resize 75% Jynx.png
convert *Electabuzz.ico[1] -resize 75% Electabuzz.png
convert *Magmar.ico[1] -resize 75% Magmar.png
convert *Pinsir.ico[1] -resize 75% Pinsir.png
convert *Tauros.ico[1] -resize 75% Tauros.png
convert *Magikarp.ico[1] -resize 75% Magikarp.png
convert *Gyarados.ico[1] -resize 75% Gyarados.png
convert *Lapras.ico[1] -resize 75% Lapras.png
convert *Ditto.ico[1] -resize 75% Ditto.png
convert *Eevee.ico[1] -resize 75% Eevee.png
convert *Vaporeon.ico[1] -resize 75% Vaporeon.png
convert *Jolteon.ico[1] -resize 75% Jolteon.png
convert *Flareon.ico[1] -resize 75% Flareon.png
convert *Porygon.ico[1] -resize 75% Porygon.png
convert *Omanyte.ico[1] -resize 75% Omanyte.png
convert *Omastar.ico[1] -resize 75% Omastar.png
convert *Kabuto.ico[1] -resize 75% Kabuto.png
convert *Kabutops.ico[1] -resize 75% Kabutops.png
convert *Aerodactyl.ico[1] -resize 75% Aerodactyl.png
convert *Snorlax.ico[1] -resize 75% Snorlax.png
convert *Articuno.ico[1] -resize 75% Articuno.png
convert *Zapdos.ico[1] -resize 75% Zapdos.png
convert *Moltres.ico[1] -resize 75% Moltres.png
convert *Dratini.ico[1] -resize 75% Dratini.png
convert *Dragonair.ico[1] -resize 75% Dragonair.png
convert *Dragonite.ico[1] -resize 75% Dragonite.png
convert *Mewtwo.ico[1] -resize 75% Mewtwo.png
convert *Mew.ico[1] -resize 75% Mew.png
